### ISSUE TITLE
Support newer IDEA versions

### ISSUE THREAD

**Issue by tamasd** [SamJakob/intellij-askama-template-plugin#3]
Hello,

The current version (2022.1.3) of CLion says that the plugin is incompatible. Do you have plans to maintain / upgrade the plugin to work with newer IDEA versions?

**Comment by SamJakob** [comment]
I'll look into it now

**Comment by SamJakob** [comment]
The new version is pending review on JetBrains Marketplace - it should go live within 2 working days.

**Comment by tamasd** [comment]
Thank you!
