### ISSUE TITLE
Faulty  "There should be a space between attribute and previous attribute" warning

### ISSUE THREAD

**Issue by freelon** [SamJakob/intellij-askama-template-plugin#6]
Hi there,
I've stumbled across a warning that, I think, shouldn't be there:

    <input class="input"
                        autocomplete="off">

produces `There should be a space between attribute and previous attribute`. This happens whenever there is not exactly one whitespace-character between two attributes and the attributes are on the same line.

Thanks for the plugin though, it's really helpful to not have to use an html plugin that messes the askama template stuff up :)

**Comment by freelon** [comment]
Hi,

No, the line break is there intentionally. When I have tags with a lot of attributes it is nice to split it on several lines. The white space between the two attributes (line break and several spaces or tabs) is where the plugin complained that it wants a space.

**Comment by SamJakob** [comment]
Oh I see, so it's not recognizing the white space?

It's presumably an issue with the newline delimiter or whitespace regex in that case.

**Comment by TheLuckyCoder** [comment]
Are there any plans to fix this? This makes the plugin almost unusable for me as it make the entire sidebar full of warnings

**Comment by SamJakob** [comment]
I haven’t managed to reproduce the problem. Are you able to provide a minimal example file that causes the problem?

**Comment by TheLuckyCoder** [comment]
Sure, I get the aforementioned warning for line 3, even when adding a space after class="" I still get the warning but pinpointed to that space char

```html
<html lang="en">
<body>
<a class=""
href=""></a>
</body>
</html>```

Hope this helps

**Comment by SamJakob** [comment]
Ah I see the problem now. This might be an issue with the grammar, I'll see if I can figure out a fix.

**Comment by sweoggy** [comment]
Thanks @SamJakob, latest version fixed the erroneous syntax warnings I had
